In [1]:
import numpy as np
from src.NN import NN
import src.utils as utils

# Settings
csv_filename = "data/seeds_dataset.csv"
hidden_layers = [1,2] # number of nodes in hidden layers i.e. [layer1, layer2, ...]
eta = 0.1 # learning rate
n_epochs = 50 # number of training epochs
n_folds = 4 # number of folds for cross-validation
seed_crossval = 1 # seed for cross-validation
seed_weights = 1 # 

In [2]:

print("Reading '{}'...".format(csv_filename))
X, y, n_classes = utils.read_csv(csv_filename, target_name="y", normalize=True)

Reading 'data/seeds_dataset.csv'...


In [5]:
# m,n=X.shape
# n
config = {
        n_classes : 25,
        "hidden_layers" : [1,2], # number of nodes in hidden layers i.e. [layer1, layer2, ...],
        "eta" : 0.1, # learning rate,
        "n_epochs" : 50, # number of training epochs,
        "n_folds" : 4 ,# number of folds for cross-validation,
        "seed_crossval" : 1 
    }

NameError: name 'n_classes' is not defined

In [4]:
config.n_clases

AttributeError: 'dict' object has no attribute 'n_clases'

In [10]:
import numpy as np
from src.NN import NN
import src.utils as utils
import copy
import random
from box import Box 
from datetime import datetime
# if(__name__ == 'main')
# Settings

def split_learn(X,y,modelConfig):
    datasets,features=X.shape
    
    splitWeights=list()
    splits = np.hsplit(X,features)
    # return splits
    print("splits made = ",len(splits))
    for o,oX in enumerate(splits):
        N, d = oX.shape

        hidden_layers = modelConfig.hidden_layers # number of nodes in hidden layers i.e. [layer1, layer2, ...]
        eta = modelConfig.eta # learning rate
        n_epochs = modelConfig.n_epochs# number of training epochs
        n_folds = modelConfig.n_folds# number of folds for cross-validation
        seed_crossval =modelConfig.seed  # seed for cross-validation
        n_classes = modelConfig.n_classes


        print("Neural network model:")
        print(" input_dim = {}".format(d))
        print(" hidden_layers = {}".format(hidden_layers))
        print(" output_dim = {}".format(n_classes))
        print(" eta = {}".format(eta))
        print(" n_epochs = {}".format(n_epochs))
        print(" n_folds = {}".format(n_folds))
        print(" seed_crossval = {}".format(seed_crossval))
        # print(" seed_weights = {}\n".format)

        # Create cross-validation folds
        idx_all = np.arange(0, N)
        idx_folds = utils.crossval_folds(N, n_folds, seed=seed_crossval) # list of list of fold indices
        
        # Train/evaluate the model on each fold
        acc_train, acc_valid = list(), list()
        print("Cross-validating with {} folds...".format(len(idx_folds)))
        for i, idx_valid in enumerate(idx_folds):
            #  seed=seed_weights
            # Collect training and test data from folds
            idx_train = np.delete(idx_all, idx_valid)
            X_train, y_train = oX[idx_train], y[idx_train]
            X_valid, y_valid = oX[idx_valid], y[idx_valid]

            # Build neural network classifier model and train
            model = NN(input_dim=d, output_dim=n_classes,
                        hidden_layers=hidden_layers)
            model.train(X_train, y_train, eta=eta, n_epochs=n_epochs)

            # Make predictions for training and test data
            ypred_train = model.predict(X_train)
            ypred_valid = model.predict(X_valid)

            # Compute training/test accuracy score from predicted values
            acc_train.append(100*np.sum(y_train==ypred_train)/len(y_train))
            acc_valid.append(100*np.sum(y_valid==ypred_valid)/len(y_valid))

            # Print cross-validation result
            print(" Fold {}/{}: acc_train = {:.2f}%, acc_valid = {:.2f}% (n_train = {}, n_valid {})".format(i+1,n_folds, acc_train[-1], acc_valid[-1], len(X_train), len(X_valid)))

        # Print results
        print(o," : ")
        print("  -> acc_train_avg = {:.2f}%, acc_valid_avg = {:.2f}%".format(sum(acc_train)/float(len(acc_train)), sum(acc_valid)/float(len(acc_valid))))

        splitWeights.append(model.get_weights())
        
    
    return splitWeights

def get_aggregate_weights(wt):
    new=[]
    
    print("wth",new)
    rep = copy.deepcopy(wt)
    for i,mx in enumerate(rep):
        # m2 = wt[i]
        if i==0:
            print("hitting new")
            new = mx
            print(new[1])
        else:
            for j,lx in enumerate(mx):
                if j==0 and i!=0:
                    # print(new[j],"88",lx)
                    #  np.concatenate((array_, add_row), axi/s=0)
                    new[j] = [np.append(new[j],lx)]
                    # print(len(new[j]),"*******************")
                else:
                    new[j] = np.add(new[j],lx)
                    print(len(new[j]))

    for k in range(len(new)):
        if not k == 0:
            print(k)
            new[k] = np.divide(new[k],len(wt))
            # print(type(l1))
    print( new )
    return new


def get_aggregate_model(shape,newWeights,modelConfig):
    # for oX in enumerate(splits):
    # print("Reading '{}'...".format(csv_filename))
    # X, y, n_classes = utils.read_csv(csv_filename, target_name="y", normalize=True)
    N, d = shape
    #   N, d = X.shape
    hidden_layers = modelConfig.hidden_layers # number of nodes in hidden layers i.e. [layer1, layer2, ...]
    eta = modelConfig.eta # learning rate
    n_epochs = modelConfig.n_epochs# number of training epochs
    n_folds = modelConfig.n_folds# number of folds for cross-validation
    seed_crossval =modelConfig.seed  # seed for cross-validation
    n_classes = modelConfig.n_classes
    print("Neural network model:")
    print(" input_dim = {}".format(d))
    print(" hidden_layers = {}".format(hidden_layers))
    print(" output_dim = {}".format(n_classes))
    print(" eta = {}".format(eta))
    print(" n_epochs = {}".format(n_epochs))
    print(" n_folds = {}".format(n_folds))
    print(" seed_crossval = {}".format(seed_crossval))

    # list of list of fold indices
    model = NN(input_dim=d, output_dim=n_classes,
                        hidden_layers=hidden_layers,AvgWeights=newWeights)
    # Train/evaluate the model on each fold
    return model


def getGenericNN(X,y,modelConfig):
    
    N, d = X.shape
    hidden_layers = modelConfig.hidden_layers # number of nodes in hidden layers i.e. [layer1, layer2, ...]
    eta = modelConfig.eta # learning rate
    n_epochs = modelConfig.n_epochs# number of training epochs
    n_folds = modelConfig.n_folds# number of folds for cross-validation
    seed_crossval =modelConfig.seed  # seed for cross-validation
    n_classes = modelConfig.n_classes

    print(" -> X.shape = {}, y.shape = {}, n_classes = {}\n".format(X.shape, y.shape, n_classes))
    print("Neural network model:")
    print(" input_dim = {}".format(d))
    print(" hidden_layers = {}".format(hidden_layers))
    print(" output_dim = {}".format(n_classes))
    print(" eta = {}".format(eta))
    print(" n_epochs = {}".format(n_epochs))
    print(" n_folds = {}".format(n_folds))
    print(" seed_crossval = {}".format(seed_crossval))

    # Create cross-validation folds
    idx_all = np.arange(0, N)
    idx_folds = utils.crossval_folds(N, n_folds, seed=seed_crossval) # list of list of fold indices

    # Train/evaluate the model on each fold
    acc_train, acc_valid = list(), list()
    print("Cross-validating with {} folds...".format(len(idx_folds)))
    for i, idx_valid in enumerate(idx_folds):

        # Collect training and test data from folds
        idx_train = np.delete(idx_all, idx_valid)
        X_train, y_train = X[idx_train], y[idx_train]
        X_valid, y_valid = X[idx_valid], y[idx_valid]

        # Build neural network classifier model and train
        model = NN(input_dim=d, output_dim=n_classes,
                hidden_layers=hidden_layers)

        model.train(X_train, y_train, eta=eta, n_epochs=n_epochs)

        # Make predictions for training and test data
        ypred_train = model.predict(X_train)
        ypred_valid = model.predict(X_valid)

        # Compute training/test accuracy score from predicted values
        acc_train.append(100*np.sum(y_train==ypred_train)/len(y_train))
        acc_valid.append(100*np.sum(y_valid==ypred_valid)/len(y_valid))

        # Print cross-validation result
        print(" Fold {}/{}: acc_train = {:.2f}%, acc_valid = {:.2f}% (n_train = {}, n_valid = {})".format(
            i+1, n_folds, acc_train[-1], acc_valid[-1], len(X_train), len(X_valid)))

    # Print results
    print("""***************************** GENERIC MODEL TRAINING RESULTS ********************\n  
    -> acc_train_avg = {:.2f}%, acc_valid_avg = {:.2f}% \n\n""".format(sum(acc_train)/float(len(acc_train)), sum(acc_valid)/float(len(acc_valid))))
    
    return model


# def main():
    # seed for cross-validation
    # csv_filename = "data/tennis.csv"
csv_filename = "data/seeds_dataset.csv"
print("Reading '{}'...".format(csv_filename))
X, y, n_c = utils.read_csv(csv_filename, target_name="y", normalize=True)
random.seed(datetime.now())
config = {
    "n_classes" : n_c,
    "hidden_layers" : [2,2], # number of nodes in hidden layers i.e. [layer1, layer2, ...],
    "eta" : 0.1, # learning rate,
    "n_epochs" : 50, # number of training epochs,
    "n_folds" : 4 ,# number of folds for cross-validation,
    "seed" : random.randrange(1,9)
}

config = Box(config)
N,d = X.shape
fold = utils.crossval_folds(N, 5, seed=config.seed) # list of list of fold indices
valid = random.randrange(0,len(fold))
validSets = fold[valid]
allSets = np.arange(0, N)
trainSets = np.delete(allSets, validSets)

nX, nY = X[trainSets], y[trainSets]
vX, vY = X[validSets], y[validSets]

genericModel = getGenericNN(nX, nY, config)
newModelWeights = split_learn(nX,nY,config)
aggregateWeights = get_aggregate_weights(newModelWeights)
newModel = get_aggregate_model(X.shape,aggregateWeights,config)
print("new weights of the aggreagated model are:", newModel.get_weights())
print ( "\n\n running predictions on validation sets held . . . . .  \n\n")
pred_generic = genericModel.predict(vX)
pred_newModel = newModel.predict(vX)

acc_generic = 100*np.sum(vY==pred_generic)/len(vY)
acc_newModel = 100*np.sum(vY==pred_newModel)/len(vY)

print("""\n*****************************FINAL VALIDATION RESULTS ********************\n  
-> accuracy_genric = {:.2f}%, acc_split_learn = {:.2f}% \n\n""".format(acc_generic,acc_newModel))


Reading 'data/seeds_dataset.csv'...
 -> X.shape = (144, 7), y.shape = (144,), n_classes = 3

Neural network model:
 input_dim = 7
 hidden_layers = [2, 2]
 output_dim = 3
 eta = 0.1
 n_epochs = 50
 n_folds = 4
 seed_crossval = 2
Cross-validating with 4 folds...
 Fold 1/4: acc_train = 68.52%, acc_valid = 55.56% (n_train = 108, n_valid = 36)
 Fold 2/4: acc_train = 33.33%, acc_valid = 25.00% (n_train = 108, n_valid = 36)
 Fold 3/4: acc_train = 75.00%, acc_valid = 69.44% (n_train = 108, n_valid = 36)
 Fold 4/4: acc_train = 69.44%, acc_valid = 69.44% (n_train = 108, n_valid = 36)
***************************** GENERIC MODEL TRAINING RESULTS ********************
  
    -> acc_train_avg = 61.57%, acc_valid_avg = 54.86% 


splits made =  7
Neural network model:
 input_dim = 1
 hidden_layers = [2, 2]
 output_dim = 3
 eta = 0.1
 n_epochs = 50
 n_folds = 4
 seed_crossval = 2
Cross-validating with 4 folds...
 Fold 1/4: acc_train = 68.52%, acc_valid = 55.56% (n_train = 108, n_valid 36)
 Fold 2/4: acc

IndexError: list index out of range

In [14]:
len(aggregateWeights[0][0])

14

In [6]:
wt[0][2][0].tolist()
# len(new[1])

[-0.15799387955905655, -1.1991673177189213]

In [7]:
# len(model.get_weights()[0][])
datasets,features=X.shape

In [22]:
new=[]
import copy
print("wth",new)
rep = copy.deepcopy(wt)
for i,mx in enumerate(rep):
    # m2 = wt[i]
    if i==0:
        print("hitting new")
        new = mx
        print(new[1])
    else:
        for j,lx in enumerate(mx):
            if j==0 and i!=0:
                # print(new[j],"88",lx)
                
                new[j] = [np.append(new[j],lx)]
                print(len(new[j]),"*******************")
            else:
                new[j] = np.add(new[j],lx)
                print(len(new[j]))

for k in range(len(new)):
    if not k == 0:
        print(k)
        new[k] = np.divide(new[k],len(wt))
        # print(type(l1))
print( new )

wth []
hitting new
[[-1.79562867]
 [ 2.32629109]]
1 *******************
2
3
1 *******************
2
3
1 *******************
2
3
1 *******************
2
3
1 *******************
2
3
1 *******************
2
3
1
2
[[array([2.8611539 , 1.88688159, 1.02089154, 3.72419257, 3.77805387,
       1.38444096, 3.11121019])], array([[0.12905778],
       [0.71185533]]), array([[-0.43778527, -0.79024719],
       [-1.4330232 , -0.35389627],
       [-0.09639481, -0.61020524]])]


In [23]:
new_nn =  NN(input_dim=features, output_dim=n_classes,
                        hidden_layers=hidden_layers,AvgWeights=new)

[2.861153897068316, 1.8868815935243572, 1.0208915413338562, 3.7241925687751216, 3.7780538720172014, 1.3844409569515108, 3.111210190876561]
[0.12905777659894133]
[0.7118553327841978]
[-0.4377852655548038, -0.7902471884649697]
[-1.4330231972115752, -0.3538962702293699]
[-0.09639481168149029, -0.6102052380595595]


In [24]:
new_nn.get_weights()

node :  {'weights': [2.861153897068316, 1.8868815935243572, 1.0208915413338562, 3.7241925687751216, 3.7780538720172014, 1.3844409569515108, 3.111210190876561], 'output': None, 'delta': None}
node :  {'weights': [0.12905777659894133], 'output': None, 'delta': None}
node :  {'weights': [0.7118553327841978], 'output': None, 'delta': None}
node :  {'weights': [-0.4377852655548038, -0.7902471884649697], 'output': None, 'delta': None}
node :  {'weights': [-1.4330231972115752, -0.3538962702293699], 'output': None, 'delta': None}
node :  {'weights': [-0.09639481168149029, -0.6102052380595595], 'output': None, 'delta': None}


[array([[2.8611539 , 1.88688159, 1.02089154, 3.72419257, 3.77805387,
         1.38444096, 3.11121019]]),
 array([[0.12905778],
        [0.71185533]]),
 array([[-0.43778527, -0.79024719],
        [-1.4330232 , -0.35389627],
        [-0.09639481, -0.61020524]])]

In [ ]:
nw = [[[2.162206105066135,
   2.511103755489059,
   1.0914315598966,
   1.299168673146784,
   1.9712199964449098,
   -0.6693635968466675,
   1.7271965968317686]],
 [[[0.6449008887629116], [1.2760450946757522]],
  [[0.6449008887629116], [1.2760450946757522]]],
 [[[-0.7172583226205111, -0.862754050663147],
   [-0.635781787018038, 0.01427466090778091],
   [-0.5019770862022626, -0.7865638296664071]],
  [[-0.7172583226205111, -0.862754050663147],
   [-0.635781787018038, 0.01427466090778091],
   [-0.5019770862022626, -0.7865638296664071]],
  [[-0.7172583226205111, -0.862754050663147],
   [-0.635781787018038, 0.01427466090778091],
   [-0.5019770862022626, -0.7865638296664071]]]]

In [ ]:
def dp(a, b):
    # print(a,b,"***^^ \n")
    return sum([float(a_ )* float(b_) for (a_, b_) in zip(a, b)])
y=[2.162206105066135,
   2.511103755489059,
   1.0914315598966,
   1.299168673146784,
   1.9712199964449098,
   -0.6693635968466675,
   1.7271965968317686]

# new[1][1]

In [ ]:
dp(new[1][0],y)

In [26]:
# for oX in enumerate(splits):
print("Reading '{}'...".format(csv_filename))
X, y, n_classes = utils.read_csv(csv_filename, target_name="y", normalize=True)
N, d = X.shape

print("Neural network model:")
print(" input_dim = {}".format(d))
print(" hidden_layers = {}".format(hidden_layers))
print(" output_dim = {}".format(n_classes))
print(" eta = {}".format(eta))
print(" n_epochs = {}".format(n_epochs))
print(" n_folds = {}".format(n_folds))
print(" seed_crossval = {}".format(seed_crossval))
print(" seed_weights = {}\n".format(seed_weights))

# Create cross-validation folds
idx_all = np.arange(0, N)
idx_folds = utils.crossval_folds(N, n_folds, seed=seed_crossval) # list of list of fold indices

# Train/evaluate the model on each fold
acc_train, acc_valid = list(), list()
print("Cross-validating with {} folds...".format(len(idx_folds)))
for i, idx_valid in enumerate(idx_folds):
#  seed=seed_weights
    # Collect training and test data from folds
    idx_train = np.delete(idx_all, idx_valid)
    X_train, y_train = X[idx_train], y[idx_train]
    X_valid, y_valid = X[idx_valid], y[idx_valid]

    # Build neural network classifier model and train
    # model = NN(input_dim=d, output_dim=n_classes,
    #             hidden_layers=hidden_layers)
    new_nn.train(X_train, y_train, eta=eta, n_epochs=n_epochs)

    # Make predictions for training and test data
    ypred_train = new_nn.predict(X_train)
    ypred_valid = new_nn.predict(X_valid)

    # Compute training/test accuracy score from predicted values
    acc_train.append(100*np.sum(y_train==ypred_train)/len(y_train))
    acc_valid.append(100*np.sum(y_valid==ypred_valid)/len(y_valid))

    # Print cross-validation result
    print(" Fold {}/{}: acc_train = {:.2f}%, acc_valid = {:.2f}% (n_train = {}, n_valid {})".format(i+1,n_folds, acc_train[-1], acc_valid[-1], len(X_train), len(X_valid)))

# Print results
# print(o," : ")
print("  -> acc_train_avg = {:.2f}%, acc_valid_avg = {:.2f}%".format(sum(acc_train)/float(len(acc_train)), sum(acc_valid)/float(len(acc_valid))))

Reading 'data/seeds_dataset.csv'...
Neural network model:
 input_dim = 7
 hidden_layers = [1, 2]
 output_dim = 3
 eta = 0.1
 n_epochs = 50
 n_folds = 4
 seed_crossval = 1
 seed_weights = 1

Cross-validating with 4 folds...
 Fold 1/4: acc_train = 68.89%, acc_valid = 59.09% (n_train = 135, n_valid 44)
 Fold 2/4: acc_train = 72.59%, acc_valid = 65.91% (n_train = 135, n_valid 44)
 Fold 3/4: acc_train = 69.63%, acc_valid = 72.73% (n_train = 135, n_valid 44)
 Fold 4/4: acc_train = 71.11%, acc_valid = 72.73% (n_train = 135, n_valid 44)
  -> acc_train_avg = 70.56%, acc_valid_avg = 67.61%


In [27]:
new_nn.get_weights()

node :  {'weights': [2.5872943666380515, 0.8850010414563316, -0.13311296759739202, -0.8379477684719221, 3.491352445580385, 0.8108488588020185, 7.10226748707677], 'output': 5.163950494216946e-05, 'delta': 2.706566185149175e-05}
node :  {'weights': [-2.9725823930843545], 'output': 0.4999616243292807, 'delta': -0.07196931755730174}
node :  {'weights': [2.8712321295483423], 'output': 0.5000370672513681, 'delta': 0.06262496641362386}
node :  {'weights': [2.599976089232433, -2.628929291267122], 'output': 0.4963316098166286, 'delta': 0.1244655031745124}
node :  {'weights': [-10.570907995730925, 3.1864178713599958], 'output': 0.02432271284028594, 'delta': 0.000577430305135766}
node :  {'weights': [5.2234668320644495, -4.944500874215855], 'output': 0.5347188494053676, 'delta': -0.11617378483881227}


[array([[ 2.58729437,  0.88500104, -0.13311297, -0.83794777,  3.49135245,
          0.81084886,  7.10226749]]),
 array([[-2.97258239],
        [ 2.87123213]]),
 array([[  2.59997609,  -2.62892929],
        [-10.570908  ,   3.18641787],
        [  5.22346683,  -4.94450087]])]

In [ ]:
new=[]
import copy
print("wth",new)
rep = copy.deepcopy(wt)
for i,mx in enumerate(rep):
    # m2 = wt[i]
    if i==0:
        print("hitting new")
        new = mx
        print(new[1])
    else:
        for j,lx in enumerate(mx):
            if j==0 and i!=0:
                # print(new[j],"88",lx)
                
                new[j] = np.append(new[j],lx)
                print(len(new[j]),"*******************")
            else:
                new[j] = np.add(new[j],lx)
                print(len(new[j]))

for k in range(len(new)):
    if not k == 0:
        print(k)
        new[k] = np.divide(new[k],len(wt))
        # print(type(l1))
print( new )

In [ ]:
rp=0
for fp in range(len(wt)):
    print(wt[fp][1])
    rp += wt[fp][1][0][0]
    print(rp)
print(rp/7)

In [ ]:
np.asarray([ 3.9273942 ,  1.9839786 ,  1.7497002 ,  3.1951442 ,  1.8707918 ,
       -0.18531519,  1.9123502 ], dtype="float32")

In [ ]:
print(type(wt[1][1]))

In [ ]:
np.asarray([ 3.9273942 ,  1.9839786 ,  1.7497002 ,  3.1951442 ,  1.8707918 ,
       -0.18531519,  1.9123502 ], dtype="float32").tolist()